language:
  - swift
osx_image: xcode12
script:
  - xcodebuild clean build test -project CovidHub.xcodeproj -scheme CovidHub -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max" ONLY_ACTIVE_ARCH=NO CODE_SIGN=NO
